[project]
name = "msrp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.2",
    "pydantic>=2.11.7",
    "rnet>=2.4.2",
]
UV_ENV_FILE =".env"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
]
