[project]
name = "msrp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.13",
    "dbt-postgres>=1.9.1",
    "jupyter>=1.1.1",
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "psycopg2>=2.9.10",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.7",
    "rnet>=2.4.2",
    "sqlalchemy>=2.0.43",
    "tenacity>=9.1.2",
]
UV_ENV_FILE =".env"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
]
